### ISSUE TITLE
retrieve_PFAM_nucleotide_sequences for 2DOI returns an error.

### ISSUE THREAD

**Issue by lemetrec** [esnapd/DegeneratePrimerTools#2]
The function retrieve_PFAM_nucleotide_sequences used for the target 2DOI (PFAM = PF01761) returns the following error:

`Error in (function (seqname, start, end, sequences = seqs)  : 
  There is an error in the ENA fasta headers or in the EMBL ID list
In addition: Warning message:
In .Call2("fasta_index", filexp_list, nrec, skip, seek.first.rec,  :
  reading FASTA file /var/folders/_f/34w14x45525c35lnnx121g6h0000gn/T//RtmpZkLgfA/filec5bb5fef448f: ignored 44 invalid one-letter sequence codes`

The command used for it was:

`dfmaster2DOI <- retrieve_PFAM_nucleotide_sequences("PF01761") #for 2DOI`

**Comment by zachcp** [comment]
Hi Christophe,

Can you try with the newest version from Github? I see the same `.Call2` error which is due to incorrectly formatted  fastafiles.  If you request a sequence that is not public yet, the REST API will include a text explanation which then triggers an error in the fasta parsing code. Similarly, incorrect sequences will do the same. However, I have included code that should catch and remove these problems. To address other, undocumented messages, I've refactored the code to print out any offending files.

Currently, on my machine I still get an error about the 44 sequences but am able to retrieve 11262 sequences. 

zach cp

**Comment by lemetrec** [comment]
Ah great, sounds good. Will try new one.

Thanks!
Christophe

**Comment by lemetrec** [comment]
It is actually giving me now an error on the Stockholm file. I just did a pull from the master...:

```
> dfmasterCapreo <- retrieve_PFAM_nucleotide_sequences("PF00155") #for Capreomycin
 Show Traceback
 
 Rerun with Debug
 Error in retrieve_PFAM_ids(pfamid, alignmenttype = alignmenttype) : 
  invalid Stockholm file
```

**Comment by zachcp** [comment]
After the pull did you install?

I get an HTTP 500 error as follows:

 Error in retrieve_PFAM_ids(., alignmenttype = alignmenttype) : 
  Invalid HTTP request. Status Code == 500. Error with PFAM server. Try later? 

The PF00155 is a big domain family and the PFAM site does not offer the alignment for all [145000 sequences](http://pfam.xfam.org/family/PF00155#alignBlock) of UNIPROT.  Can you try:

seqs <- retrieve_PFAM_nucleotide_sequences("PF00155", alignmenttype="seed")

or

seqs <- retrieve_PFAM_nucleotide_sequences("PF00155", alignmenttype="full")

**Comment by lemetrec** [comment]
Yes it seems installed properly, I can run the PEP just fine.
running it with the "full" alignment type returns an error for "invalid Stockholm file"

The seed does return a few warnings but populates the DF with 134 sequences (though some are empty)
